// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimberHaul.API.Data;

#nullable disable

namespace TimberHaul.API.Migrations
{
    [DbContext(typeof(TimberHaulDbContext))]
    [Migration("20251118003436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "equipment_type", new[] { "chainsaw", "truck", "winch", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "load_status", new[] { "pending", "on_truck", "in_transit", "delivered" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "cash", "card", "bank_transfer", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "unpaid", "paid", "overdue" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "forester", "delivery", "customer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wood_type", new[] { "oak", "beech", "pine", "spruce", "birch", "other" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimberHaul.API.Models.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cart_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_unit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("cart_items");
                });

            modelBuilder.Entity("TimberHaul.API.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_profiles");
                });

            modelBuilder.Entity("TimberHaul.API.Models.DeliveryProfile", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_number");

                    b.Property<decimal>("Rating")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rating");

                    b.Property<int>("TotalDeliveries")
                        .HasColumnType("integer")
                        .HasColumnName("total_deliveries");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_plate");

                    b.HasKey("DriverId");

                    b.ToTable("delivery_profiles");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("equipment_name");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_service_date");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<DateTime?>("NextServiceDue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_service_due");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("RuntimeHours")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_hours");

                    b.Property<int?>("ServiceIntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("service_interval_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EquipmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForestPlot", b =>
                {
                    b.Property<Guid>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("PlotName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("plot_name");

                    b.Property<decimal?>("TotalArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_area");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlotId");

                    b.HasIndex("ForesterId");

                    b.ToTable("forest_plots");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForesterProfile", b =>
                {
                    b.Property<Guid>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<decimal>("TotalWoodAvailable")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_wood_available");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ForesterId");

                    b.ToTable("forester_profiles");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Load", b =>
                {
                    b.Property<Guid>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("load_id");

                    b.Property<string>("BeforeLoadPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("before_load_photo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveredPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivered_photo");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_location");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<string>("LoadNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("load_number");

                    b.Property<DateTime?>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OnTruckPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("on_truck_photo");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<decimal>("PricePerCubicMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_cubic_meter");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume");

                    b.Property<int>("WoodType")
                        .HasColumnType("integer")
                        .HasColumnName("wood_type");

                    b.HasKey("LoadId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("ForesterId");

                    b.HasIndex("LoadNumber")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("PlotId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.ToTable("loads");
                });

            modelBuilder.Entity("TimberHaul.API.Models.MaintenanceLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("maintenance_type");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.HasKey("LogId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("maintenance_log");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text")
                        .HasColumnName("customer_notes");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_city");

                    b.Property<string>("DeliveryPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_postal_code");

                    b.Property<Guid?>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_status");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_unit");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ForesterId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderStatus");

                    b.HasIndex("ProductId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid?>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("load_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentMethodType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ForesterId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("LoadId");

                    b.HasIndex("Status");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("AvailableStock")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("available_stock");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("MinOrderVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("min_order_volume");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_unit");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_image");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WoodType")
                        .HasColumnType("integer")
                        .HasColumnName("wood_type");

                    b.HasKey("ProductId");

                    b.HasIndex("ForesterId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("ProductName");

                    b.HasIndex("WoodType");

                    b.ToTable("products");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("load_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("ReviewId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("TimberHaul.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TimberHaul.API.Models.WoodInventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<decimal>("AvailableVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("available_volume");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ForesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("forester_id");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("ReservedVolume")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("reserved_volume");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryId");

                    b.HasIndex("ForesterId");

                    b.HasIndex("PlotId");

                    b.HasIndex("ProductId");

                    b.ToTable("wood_inventory");
                });

            modelBuilder.Entity("TimberHaul.API.Models.CartItem", b =>
                {
                    b.HasOne("TimberHaul.API.Models.CustomerProfile", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimberHaul.API.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TimberHaul.API.Models.CustomerProfile", b =>
                {
                    b.HasOne("TimberHaul.API.Models.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("TimberHaul.API.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimberHaul.API.Models.DeliveryProfile", b =>
                {
                    b.HasOne("TimberHaul.API.Models.User", "User")
                        .WithOne("DeliveryProfile")
                        .HasForeignKey("TimberHaul.API.Models.DeliveryProfile", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Equipment", b =>
                {
                    b.HasOne("TimberHaul.API.Models.User", "Owner")
                        .WithMany("Equipment")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForestPlot", b =>
                {
                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("ForestPlots")
                        .HasForeignKey("ForesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forester");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForesterProfile", b =>
                {
                    b.HasOne("TimberHaul.API.Models.User", "User")
                        .WithOne("ForesterProfile")
                        .HasForeignKey("TimberHaul.API.Models.ForesterProfile", "ForesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Load", b =>
                {
                    b.HasOne("TimberHaul.API.Models.CustomerProfile", "Customer")
                        .WithMany("Loads")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TimberHaul.API.Models.DeliveryProfile", "Driver")
                        .WithMany("Loads")
                        .HasForeignKey("DriverId");

                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("Loads")
                        .HasForeignKey("ForesterId");

                    b.HasOne("TimberHaul.API.Models.Order", "Order")
                        .WithMany("Loads")
                        .HasForeignKey("OrderId");

                    b.HasOne("TimberHaul.API.Models.ForestPlot", "Plot")
                        .WithMany("Loads")
                        .HasForeignKey("PlotId");

                    b.HasOne("TimberHaul.API.Models.Product", "Product")
                        .WithMany("Loads")
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Forester");

                    b.Navigation("Order");

                    b.Navigation("Plot");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TimberHaul.API.Models.MaintenanceLog", b =>
                {
                    b.HasOne("TimberHaul.API.Models.Equipment", "Equipment")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimberHaul.API.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy");

                    b.Navigation("Equipment");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Order", b =>
                {
                    b.HasOne("TimberHaul.API.Models.CustomerProfile", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("Orders")
                        .HasForeignKey("ForesterId");

                    b.HasOne("TimberHaul.API.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("Forester");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Payment", b =>
                {
                    b.HasOne("TimberHaul.API.Models.CustomerProfile", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("Payments")
                        .HasForeignKey("ForesterId");

                    b.HasOne("TimberHaul.API.Models.Load", "Load")
                        .WithMany("Payments")
                        .HasForeignKey("LoadId");

                    b.Navigation("Customer");

                    b.Navigation("Forester");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Product", b =>
                {
                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("Products")
                        .HasForeignKey("ForesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forester");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Review", b =>
                {
                    b.HasOne("TimberHaul.API.Models.CustomerProfile", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimberHaul.API.Models.DeliveryProfile", "Driver")
                        .WithMany("Reviews")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimberHaul.API.Models.Load", "Load")
                        .WithMany("Reviews")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("TimberHaul.API.Models.WoodInventory", b =>
                {
                    b.HasOne("TimberHaul.API.Models.ForesterProfile", "Forester")
                        .WithMany("WoodInventories")
                        .HasForeignKey("ForesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimberHaul.API.Models.ForestPlot", "Plot")
                        .WithMany("WoodInventories")
                        .HasForeignKey("PlotId");

                    b.HasOne("TimberHaul.API.Models.Product", "Product")
                        .WithMany("WoodInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forester");

                    b.Navigation("Plot");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TimberHaul.API.Models.CustomerProfile", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Loads");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TimberHaul.API.Models.DeliveryProfile", b =>
                {
                    b.Navigation("Loads");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Equipment", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForestPlot", b =>
                {
                    b.Navigation("Loads");

                    b.Navigation("WoodInventories");
                });

            modelBuilder.Entity("TimberHaul.API.Models.ForesterProfile", b =>
                {
                    b.Navigation("ForestPlots");

                    b.Navigation("Loads");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Products");

                    b.Navigation("WoodInventories");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Load", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Order", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("TimberHaul.API.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Loads");

                    b.Navigation("Orders");

                    b.Navigation("WoodInventories");
                });

            modelBuilder.Entity("TimberHaul.API.Models.User", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("DeliveryProfile");

                    b.Navigation("Equipment");

                    b.Navigation("ForesterProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
